import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by FlutterFire CLI for mazonn-ecommerce-and-pos.
class DefaultFirebaseOptions {
  static bool get isConfigured =>
      android.apiKey != 'YOUR_API_KEY' && android.projectId != 'YOUR_PROJECT_ID';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UCk21XdiHr1SBiZtrbUg3x2n_6cJyBw',
    appId: '1:1034972929409:android:3ca790294cc342e0fa1c80',
    messagingSenderId: '1034972929409',
    projectId: 'mazonn-ecommerce-and-pos',
    storageBucket: 'mazonn-ecommerce-and-pos.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MUhFeftNoHPPOmgauhM4qB1Q3GGjvO8',
    appId: '1:1034972929409:ios:fa62b87d7ca5d7a2fa1c80',
    messagingSenderId: '1034972929409',
    projectId: 'mazonn-ecommerce-and-pos',
    storageBucket: 'mazonn-ecommerce-and-pos.firebasestorage.app',
    iosBundleId: 'com.example.mazonEcommercePosEcosystem',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABj4yVGvG1bp5vo8H6h1CE2ze8F6dTpP4',
    appId: '1:1034972929409:web:3e9207384039c3f7fa1c80',
    messagingSenderId: '1034972929409',
    projectId: 'mazonn-ecommerce-and-pos',
    authDomain: 'mazonn-ecommerce-and-pos.firebaseapp.com',
    storageBucket: 'mazonn-ecommerce-and-pos.firebasestorage.app',
    measurementId: 'G-8T9YLJQ03H',
  );
}
